doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    types:
      Id:
        class: App\Modules\Product\Infrastructure\Persistence\Doctrine\Types\IdType
      SimpleString:
        class: App\Modules\Product\Infrastructure\Persistence\Doctrine\Types\SimpleStringType
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      product_domain:
        mapping: true
        type: xml
        dir: "%kernel.project_dir%/src/Modules/Product/Infrastructure/Persistence/Doctrine/Mapping/Domain"
        prefix: 'App\Modules\Product\Domain'
        is_bundle: false
      product_infrastructure:
        mapping: true
        type: xml
        dir: "%kernel.project_dir%/src/Modules/Product/Infrastructure/Persistence/Doctrine/Mapping/Infrastructure"
        prefix: 'App\Modules\Product\Infrastructure\Persistence\Doctrine\Entity'
        is_bundle: false

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool
  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
